# Generated by Django 3.1 on 2020-08-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('useremail', models.EmailField(max_length=30, primary_key=True, serialize=False, verbose_name='이메일(아이디)')),
                ('username', models.CharField(max_length=12, verbose_name='사용자 이름')),
                ('password', models.CharField(max_length=12, verbose_name='비밀 번호')),
                ('registered_dttm', models.DateField(auto_now_add=True, verbose_name='가입 시간')),
            ],
        ),
    ]
