# Generated by Django 3.1 on 2020-08-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(null=True)),
                ('gender', models.TextField()),
                ('feature', models.TextField()),
                ('phone', models.IntegerField()),
                ('place', models.TextField()),
                ('photo', models.FileField(blank=True, upload_to='photo_%Y_%m_%d')),
            ],
        ),
    ]
