# Generated by Django 3.1 on 2020-09-02 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0002_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
